### ISSUE TITLE
docs/customizations/layout is TODO

### ISSUE THREAD

**Issue by ajnart** [ajnart/homarr-docs#20]
### Environment

Docker

### Describe the problem

https://homarr-docs-6cp0espln-ajnart.vercel.app/docs/customizations/layout

### Please tick the boxes

- [X] You've read the [docs](https://github.com/ajnart/homarr#readme)
- [X] You've checked for [duplicate issues](https://github.com/ajnart/homarr/issues)
- [X] You've tried to debug yourself

**Comment by walkxcode** [comment]
Hello sir, Mr. Dr. Ajnart, this is now fixed https://homarr-docs-lmand7ilp-ajnart.vercel.app/docs/customizations/layout
